version: '2.2'

services:
  bridge:
    image: debian
    restart: always
    volumes:
      - /home/abe/code/inventory-bridge:/opt/inventory-bridge
    environment:
      - PGHOST=10.28.0.202
      - PGDATABSE=inventory
      - PGUSER=inventory
      - PGPASSWORD=devpass
      - PORT=3548
    network_mode: bridge